# To be built
LOCAL_TARGET    =  test1
LOCAL_SOTARGET  =
LOCAL_OBJS      = test1.o

# Control.
LOCAL_LIBS      = -lxlate-jobs -lutils \
		  -lboost_thread -lboost_system -lboost_filesystem -lboost_iostreams -lboost_log
LOCAL_LIBPATH   = -L$(PROJECT_ROOT)/lib
LOCAL_INCPATH   = -I$(PROJECT_ROOT)/src/cpp/include/
LOCAL_DEFINES   = -DBOOST_ALL_DYN_LINK
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  = 
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules
