# To be built
LOCAL_TARGET    = test1-tpool
LOCAL_SOTARGET  =
LOCAL_OBJS      = test1-tpool.o

# Control.
LOCAL_LIBS      = 
LOCAL_LIBPATH   = 
LOCAL_INCPATH   =-I$(PROJECT_ROOT)/src/cpp/include
LOCAL_DEFINES   = 
LOCAL_CXXFLAGS  =
LOCAL_CPPFLAGS  =
LOCAL_LDFLAGS   =
LOCAL_LDSOFLAGS =

include $(ENV_ROOT)/makerules/build.rules

